### ISSUE TITLE
Update pipeline actions that will be deprecated soon

### ISSUE THREAD

**Issue by mabulgu** [strimzi/kafka-access-operator#24]
I think these actions will be soon deprecated. IT would be great to update them to newer versions such as in https://github.com/strimzi/strimzi-kafka-operator/pull/8321 => but can be done also in later PR.

_Originally posted by @scholzj in https://github.com/strimzi/kafka-access-operator/pull/22#discussion_r1206033256_

**Comment by mabulgu** [comment]
@mkurtcs (Mustafa) wants to work on this starter issue if you don't mind. I will also try to review this as we follow a mentorship program with Mustafa.

 @scholzj @katheris jfyi

**Comment by katheris** [comment]
@mabulgu @mkurtcs how are you getting on with this issue?

**Comment by mabulgu** [comment]
> @mabulgu @mkurtcs how are you getting on with this issue?

@katheris let me contact him and decide here. If he cannot continue this anymore, I can create a quick PR.

**Comment by mabulgu** [comment]
@katheris I am gonna create a quick PR for this ASAP. @mkurtcs said he wouldn't be able to look at this anymore.

**Comment by mabulgu** [comment]
@katheris I've created this PR: https://github.com/strimzi/kafka-access-operator/pull/34

Pls check when available and let me know if I am missing sth or sth extra needed.
