### ISSUE TITLE
Helm chart for kafka-access-operator

### ISSUE THREAD

**Issue by jcpunk** [strimzi/kafka-access-operator#25]
It would be nice if there was a helm chart for this project.

**Comment by scholzj** [comment]
That might happen one day. But it is still in the initial work stage without any release. So I don't think Helm chart makes much sense right now. Unfortunately, we did not have too much time to work on this lately.

**Comment by sebastiangaiser** [comment]
When the initial release of the operator is done, I would offer my help writing a Helm chart.
