### ISSUE TITLE
Initial release of Kafka Access Operator

### ISSUE THREAD

**Issue by katheris** [strimzi/kafka-access-operator#33]
An issue to track the initial release.

Release version: 0.1.0
Present features
 - Access Operator creates a Kubernetes Secret with connection information
 - Connection information includes bootstrap servers
 - Access Operator chooses a suitable listener if that is omitted from the CR
 - Access Operator takes into account KafkaUser if included in the CR
 - All KafkaUser types scram 512, tls and tls-external all supported
 - Kubernetes secret includes sasl jaas config for scram 512 user
 - Kubernetes secret contains pem certificate files and keystore key

Missing features
 - Kubernetes secret does not contain PKCS12 files (we will only add this in future if users request it)

Outstanding work before release:
 - Flesh out README.md to list above features and known limitations
 - Integration tests that run on minikube
 - Update Strimzi docs to include reference to Access Operator

**Comment by katheris** [comment]
@strimzi/maintainers  I've tried to capture the state of the component and what work I think is outstanding before a release. I'd be interested to know what you think, have I missed something, are there other features that we should definitely implement before an initial release?

**Comment by scholzj** [comment]
So, would `Kubernetes secret does not contain any certificates` be implemented for 0.1.0? As for the other items ... I think we do not absolutely need to have it covered in Strimzi docs before a 0.1.0 release. The README file should work as docs for the time being. As for the tests, we should have some test coverage, but I think it is up for discussion what exactly the coverage should be.

**Comment by scholzj** [comment]
We should also try to bump the dependencies with CVEs before the release. Kafka and Jetty.

**Comment by katheris** [comment]
>So, would Kubernetes secret does not contain any certificates be implemented for 0.1.0?

I'm proposing that we don't implement this before 0.1.0, only because I was starting from the features we have now. But happy to add that to the list of things we should do before the release.

>As for the tests, we should have some test coverage, but I think it is up for discussion what exactly the coverage should be.

Currently we do have unit tests which I think does provide a good level of coverage of our code, however I have felt the need to run it end to end just to verify that the integration with the Java Operator SDK is working, so that would be my argument for at least a basic integration test that actually stands the operator up, creates a KafkaAccess and checks the secret exists.

**Comment by scholzj** [comment]
> I'm proposing that we don't implement this before 0.1.0, only because I was starting from the features we have now. But happy to add that to the list of things we should do before the release.

I guess I would need to understand what exactly it means to properly judge it. Does it mean that it works only with PLAIN listeners and SCRAM-SHA authentication?

**Comment by katheris** [comment]
It means that for all user types and for plain listeners you get the bootstrap servers address, and the security protocol in the Kafka Access secret and for SCRAM-SHA authentication users you also get the sasl jaas config and SASL mechanism

**Comment by katheris** [comment]
I think the existing value is:

- support for service binding operator
- users don't have to parse the Kafka CR to find the correct listener
- applications can get their configuration (apart from certificates) from a single secret

For certificates I don't know how Strimzi users usually use them in their application, e.g. do they want to mount a secret containing the certificates, or do they usually build a truststore that trusts their CA as part of their build process when building the app? However it is part of the proposal I originally created so I'm happy to add it to the list of required features for the release. Do you think it would be worth bringing it up at the Strimzi community call to see what others think?

I can also check if I have a branch somewhere with the code to copy the certificates already, it might be a quick update to make

**Comment by scholzj** [comment]
My _concern_ is that from my experience, PLAINTEXT users with SCRAM-SHA authentication will be a very small share of our users. And while it will work also for the other users, it will have not much real value for them as their issue is with the certificate delivery and not with the bootstrap address. If they get all the other information, the bootstrap address would be a nice thing to set on top of it. But I don't think anyone will care about it if they have to copy the certificates every time they change because that will be way more manual work than finding the bootstrap address once at the beginning. Especially when you combine it with the effort of learning how to use it, but also the effort of running the Access Operator. 

As I said, if you want to do a first release without it that is fine. But I would not expect it to attract many users because it from my point of view does not solve the main issues they have.

----

>For certificates I don't know how Strimzi users usually use them in their application, e.g. do they want to mount a secret containing the certificates, or do they usually build a truststore that trusts their CA as part of their build process when building the app? However it is part of the proposal I originally created so I'm happy to add it to the list of required features for the release. Do you think it would be worth bringing it up at the Strimzi community call to see what others think?

Java now supports PEM certificates. So I think we should maybe for a start try to cover those and skip the PKCS12 files. If they use their own CA, I do not think we care too much about them as they already have it and can take care of it in any way they want. The main concern would be the Strimzi CA and mTLS certificates.

Yes, we can discuss this on the community call.

**Comment by katheris** [comment]
Looking back over the code and the proposal I think you're right that we should include certificates. For the first release I think it makes sense to fully implement the proposal and it doesn't look like much work to add the certificates so shouldn't delay a release much.

In terms of which certificates we use, the original proposal had:
```
ssl.truststore.crt: #  Strimzi cluster CA certificate (copied from ca.crt in <clustername>-cluster-ca-cert secret)
ssl.truststore.p12: #  PKCS #12 archive file for Strimzi cluster CA certificate (copied from ca.p12 in <clustername>-cluster-ca-cert secret)
ssl.truststore.password: # Password for protecting the Strimzi cluster CA certificate PKCS #12 archive file (copied from ca.password in <clustername>-cluster-ca-cert secret)
# Provided if selected user is mTLS:
ssl.keystore.p12: # client certificate for the consuming client PKCS #12 archive file for storing certificates and keys (copied from user.p12 in KafkaUser secret)
ssl.keystore.password: # password for protecting the client certificate PKCS #12 archive file (copied from user.password in KafkaUser secret)
ssl.keystore.crt: # certificate for the consuming client signed by the clients' CA (copied from user.crt in KafkaUser secret)
ssl.keystore.key: # private key for the consuming client (copied from user.key in KafkaUser secret)
```

So we were including both pem and PKCS12 files. Perhaps on the community call we can just discuss whether the .p12 files are still needed or whether .crt is enough

**Comment by scholzj** [comment]
I guess technically they are not needed anymore. But users might be looking for them not knowing how to use the PEM files. So the question is how well can we deal with it.

**Comment by katheris** [comment]
During the community call on the 7th September we decided to initially add pem files, but not PKCS12 and then wait to see if community members request it.

**Comment by sebastiangaiser** [comment]
What is the status for the initial release?

**Comment by juv** [comment]
Hi, I'm looking forward to use this operator 👍. Is it planned to include this into RedHat AMQ Streams bundle too? This would make using it very easy for existing customers.

**Comment by sebastiangaiser** [comment]
It was added to the [minutes meeting](https://docs.google.com/document/d/1V1lMeMwn6d2x1LKxyydhjo2c_IFANveelLD880A6bYc/edit) for 2024/04/18. However, it was rescheduled for the 2024/05/02.

**Comment by ppatierno** [comment]
> Hi, I'm looking forward to use this operator 👍. Is it planned to include this into RedHat AMQ Streams bundle too? This would make using it very easy for existing customers.

This is an open source project as part of Strimzi. Even if it will have an initial release at somepoint we cannot say if it's going to be part or not of a vendor specific bundle/offer.

**Comment by katheris** [comment]
In terms of an initial release of this component, the main outstanding piece of work is the system tests. I've added https://github.com/strimzi/kafka-access-operator/issues/46 to track that work. We hope to make progress on it soon.

**Comment by ryanfaircloth** [comment]
Wondering if this died or is going to be part of strimzi-operator it is useful

**Comment by scholzj** [comment]
I think we will try to get the first release soon.

**Comment by ryanfaircloth** [comment]
This would be so helpful, today I am creating users in the namespace where the kafka cluster is then using reflector to copy the secrets it works most of the time except when it doesn't then I have outages

**Comment by Crazy-Hopper** [comment]
Hello! I'm not sure if this is the right place to write this or not, so pardon me if it's the latter 😄

I stumbled upon this project in an attempt to find a better and more native/official alternative to strimzi-registry-operator by lsst-sqre. Of course this operator won't deploy the SR itself, but having deployed it manually and pointing to the secret from this operator could be a working plan. The only lacking parts I can see at the moment are:
- jks stores (maybe SR could consume PKCS12 instead, didn't dig into this topic deeply)
- some sort of notification upon contents change of the secret (to restart the depending SR)

I'd be happy to hear any suggestions you might have on this topic.

**Comment by scholzj** [comment]
MAybe starting a new issue or a dicussion (https://github.com/orgs/strimzi/discussions) would be the best start instead of commenting on unrelated issue. Assuming your schema registry is Java based (bassed on you asking for JKS), it can use PKCS12 files as well.

**Comment by katheris** [comment]
We now have our first official release, so closing this issue

https://github.com/strimzi/kafka-access-operator/releases/tag/0.1.0
