### ISSUE TITLE
Better status condition management

### ISSUE THREAD

**Issue by lburgazzoli** [strimzi/kafka-access-operator#41]
With https://github.com/strimzi/kafka-access-operator/pull/37,  the  KafkaAccess resource has now a `Ready` condition, however , the `setLastTransitionTime` is always updated with the invocation time of the [setReadyCondition](https://github.com/strimzi/kafka-access-operator/blob/50a2489e0f2f0685e649bcc756847f6f346a60bd/src/main/java/io/strimzi/kafka/access/model/KafkaAccessStatus.java#L68) method, however such field is meant to report the last time the condition changed from one status to another. 

A side effect is that, since the status always changes, then additional events are generated by the API Server and observing controllers may have to deal with superflous updates.

Ideally we could follow what it is done in the Kubernetes [apimachinery codebase ](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/conditions.go#L25-L68).

I can work on a PR  if this make sense.

**Comment by katheris** [comment]
Hi @lburgazzoli, thanks for raising this. I agree that the condition ought to have it's last transition time set when it becomes ready, not on every update. I'm happy for you to work on a PR for this. I haven't had a chance to check if Java Operator SDK provides any API to help with this, but might be worth checking

**Comment by lburgazzoli** [comment]
I will check with the JOSDK team, eventually we can add such functionality there (however in this case, we are sing conditions from the Strimzi SDK so it won't probably be able to leverage JOSDK)
