### ISSUE TITLE
Add system tests

### ISSUE THREAD

**Issue by katheris** [strimzi/kafka-access-operator#46]
Currently the operator only contains unit tests, it does not have any tests that see how it works in a real Kubernetes cluster.

We should add some system tests to the repository that can run against a local minikube. This can be similar to the way that system tests work in the Strimzi cluster operator. Similar to the drain cleaner tests, rather than deploying an actual instance of the Strimzi cluster operator the tests can:

- Install the Strimzi CRDs into the Kubernetes cluster
- Create instances of Kafka and KafkaUser CRs including the status fields
- Create Kubernetes Secrets that match what the cluster operator would create
- Deploy the Kafka access operator and make sure it creates the secret we expect with the correct data

**Comment by im-konge** [comment]
Done in #48
